# Generated by Django 4.1.1 on 2022-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('on_clicks',)},
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
