# Generated by Django 4.1.1 on 2022-09-16 02:08

from django.db import migrations, models
import os

path_query = os.path.join(os.path.dirname(__file__), 'queries', 'sql_generator.text')
with open(path_query, 'r') as f:
    query = f.read()
    
class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_alter_url_options_alter_url_short_url'),
    ]

    operations = [
        migrations.RunSQL(
            sql=query,
        )
    ]
